# Generated by Django 6.1.1 on 2026-09-24 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.IntegerField(max_length=10)),
                ('imagem', models.ImageField(upload_to='fotos/curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.departamento'),
        ),
    ]
