# Generated by Django 6.1.1 on 2026-09-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_departamento_curso_departamento'),
        ('estudantes', '0002_rename_data_nascimento_estudante_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='estudante',
            field=models.ManyToManyField(blank=True, to='estudantes.estudante'),
        ),
    ]
