# Generated by Django 6.1.1 on 2026-09-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_disciplina_estudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='imagem',
            field=models.ImageField(upload_to='fotos/departamento'),
        ),
    ]
