# Generated by Django 6.1.1 on 2026-09-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('foto', models.ImageField(default='foto.png', upload_to='fotos/estudantes')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
