# Generated by Django 6.1.1 on 2026-09-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='data_nascimento',
            new_name='nascimento',
        ),
    ]
